apiVersion: v1
kind: Service
metadata:
  name: deployledger-api
  namespace: deployledger
  labels:
    app.kubernetes.io/name: deployledger-api
spec:
  selector:
    app.kubernetes.io/name: deployledger-api
  ports:
    - name: http
      port: 8000
      targetPort: http

