apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deployledger
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - api-serviceaccount.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/managed-by: kustomize

