apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deployledger-staging
resources:
  - ../../base
patches:
  - target:
      kind: Namespace
      name: deployledger
    patch: |-
      - op: replace
        path: /metadata/name
        value: deployledger-staging
  - target:
      kind: Deployment
      name: deployledger-api
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: deployledger-staging
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/kyan9400/deployledger-api:0.1.0
  - target:
      kind: Deployment
      name: deployledger-web
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: deployledger-staging
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/kyan9400/deployledger-web:0.1.0

